<a href="https://colab.research.google.com/github/akulvibhore/flyrank-ml-internship-/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/akulvibhore/flyrank-ml-internship-/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task

### Lane: Refresh / Content Opportunity Scoring

My chosen lane is **Refresh / Content Opportunity Scoring**.

The ML task type is **scoring**.

The goal is to assign each content page an opportunity score that estimates how strongly that page should be considered for a content action such as:

- Refresh
- Expand
- Protect
- Prune
- Monitor

The unit of analysis is **one content page**.

Instead of using a single fixed rule such as "refresh every page with low traffic", the model can combine multiple signals such as search demand, competition, content length, CTR, average position, engagement, scroll behaviour, AI traffic, and trend information.

The output of the model would be a **ranked review queue** of content pages, so that the highest-priority opportunities can be reviewed first.

In [46]:
import pandas as pd
import numpy as np

df = pd.read_csv("content_refresh_anonymized.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 2. Target or proxy


The ideal target would be a future outcome that tells us whether a content page benefited from a refresh.

For example, the target could be the **change in organic sessions or engagement after a content refresh**.

However, the starter dataset does not contain a direct "successful refresh" outcome for every page. Therefore, for this framing exercise, I would use a **proxy opportunity score** based on observable signals in the dataset.

The proxy should represent the potential value of taking action on a page.

Relevant signals include:

- Search volume
- Competition
- CPC
- Word count
- Character count
- CTR
- Average position
- Engagement rate
- Scroll rate
- AI traffic percentage
- Trend direction
- Trend percentage

A future version of the project could replace this proxy with a measured outcome such as:

**Target = change in organic sessions / engagement after the page is refreshed.**

This would make the problem a supervised ML task because the model could learn from historical page outcomes.

In [38]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles and folders here:")
print(os.listdir())

Current working directory:
/content

Files and folders here:
['.config', 'content_refresh_anonymized.csv', 'content_refresh_anonymized (1).csv', 'sample_data']

In [39]:
import os

matches = []

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file == "content_refresh_anonymized.csv":
            matches.append(os.path.join(root, file))

print("Found files:")
for path in matches:
    print(path)

Found files:
/content/content_refresh_anonymized.csv

In [40]:
!git clone https://github.com/flyrank/flyrank-data.git

Cloning into 'flyrank-data'...
fatal: could not read Username for 'https://github.com': No such device or address

In [41]:
!find /content/flyrank-data -type f | head -50

find: ‘/content/flyrank-data’: No such file or directory

In [42]:
import os

print("Checking /content...")
print()

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

Checking /content...

/content/content_refresh_anonymized.csv
/content/content_refresh_anonymized (1).csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_train.csv

In [43]:
import os

print("Does /content/flyrank-data exist?")
print(os.path.exists("/content/flyrank-data"))

print("\nContents of /content:")
print(os.listdir("/content"))

Does /content/flyrank-data exist?
False

Contents of /content:
['.config', 'content_refresh_anonymized.csv', 'content_refresh_anonymized (1).csv', 'sample_data']

In [44]:
!git clone https://github.com/flyrank/flyrank-data.git /content/flyrank-data

Cloning into '/content/flyrank-data'...
fatal: could not read Username for 'https://github.com': No such device or address

In [45]:
import os

for root, dirs, files in os.walk("/content/flyrank-data"):
    for file in files:
        print(os.path.join(root, file))

In [31]:
from google.colab import files

uploaded = files.upload()

Saving content_refresh_anonymized.csv to content_refresh_anonymized (1).csv

In [32]:
import pandas as pd
import numpy as np

df = pd.read_csv("content_refresh_anonymized.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [33]:
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

## 3. Success metric

The main success metric for this scoring task is **Precision@K**.

K represents the number of pages the content team can realistically review in a given period. For example, if the team can review 100 pages, Precision@100 measures the proportion of those top 100 scored pages that later show a meaningful positive outcome after the content action.

This metric fits the task because the output is a ranked list and the content team has limited capacity.

For the future supervised version of this task, a good result would mean that a high proportion of the pages near the top of the ranked list actually benefit from a refresh.

A secondary business measure could be the change in sessions or engagement after a refresh, but **Precision@K** is the primary metric for evaluating the ranking.

In [34]:
# Check the number of content pages available for ranking

print("Number of content pages:", len(df))
print("Example review capacity (K): 100")
print("Primary success metric: Precision@100")

Number of content pages: 30000
Example review capacity (K): 100
Primary success metric: Precision@100

## 4. The unit of analysis, as a real dataframe


The unit of analysis is **one content page**.

Each row represents one content page and contains its search, content, performance, engagement, freshness, and trend signals.

For this lane, I will use the columns that are relevant to identifying content opportunity.

The dataframe below shows the actual page-level observations used for the framing exercise.

Therefore:

**One row = one content page.**

The eventual scoring output would assign one opportunity score to each content page and use those scores to create a ranked review queue.

In [35]:
# Select the page-level fields relevant to content opportunity scoring

lane_columns = [
    "content_id",
    "search_volume",
    "competition",
    "competition_level",
    "cpc",
    "content_type",
    "main_intent",
    "word_count",
    "char_count",
    "impressions_90d",
    "clicks_90d",
    "sessions_90d",
    "engaged_sessions_90d",
    "content_age_days",
    "days_since_last_update",
    "freshness_tier",
    "ctr",
    "avg_position",
    "engagement_rate",
    "scroll_rate",
    "ai_traffic_pct",
    "trend_direction",
    "trend_pct"
]

lane_df = df[lane_columns].copy()

print("Unit of analysis: one content page")
print("Lane dataframe shape:", lane_df.shape)

display(lane_df.head(10))

Unit of analysis: one content page
Lane dataframe shape: (30000, 23)

,content_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,impressions_90d,...,content_age_days,days_since_last_update,freshness_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,trend_direction,trend_pct
0,content_304f48230142,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,3803,...,187,20,0-30,0.76,10.6,5.88,4.55,0.0,down,-41.4
1,content_a1fb4e703a9e,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,15320,...,445,25,0-30,0.05,20.3,0.00,10.00,0.0,down,-57.7
2,content_9aa793d4d895,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,12581,...,141,20,0-30,0.09,36.5,0.00,28.57,0.0,down,-60.9
3,content_331d6c4de07b,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,11751,...,463,22,0-30,0.49,6.2,1.28,3.45,0.0,stable,-13.8
4,content_d99b7a2d90ca,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,19140,...,263,14,0-30,0.13,44.0,0.00,24.29,0.0,down,-34.7
5,content_d4084a4bc775,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,3970,...,147,20,0-30,0.03,8.5,0.00,25.00,0.0,down,-38.9
6,content_9a34b442b552,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,20,...,90,20,0-30,0.00,7.0,0.00,0.00,0.0,down,-92.3
7,content_a63219c6e95a,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,1724,...,445,22,0-30,0.06,21.2,3.57,7.14,0.0,stable,0.6
8,content_5e6c160719bc,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,32574,...,90,20,0-30,0.09,46.0,5.88,6.25,0.0,down,-58.8
9,content_c27558df2b0c,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,1240,...,257,104,91-180,0.16,4.9,0.00,0.00,0.0,down,-29.2

## 5. Why ML beats a fixed rule here

## 5. Why ML beats a fixed rule here

A fixed rule might say:

> "Refresh every page with a low CTR."

The problem is that content opportunity depends on multiple signals at the same time.

For example, a page can have a low CTR but also have high search volume, a strong average position, increasing demand, and good engagement. Another page may have low traffic simply because there is very little search demand.

The dataset contains multiple signals including search volume, competition, content length, CTR, average position, engagement rate, scroll rate, AI traffic, freshness, and recent trends.

A single if-statement would require manually choosing thresholds for these variables and would not easily capture how they interact.

ML is useful here because a future model could learn relationships between these signals and a measured post-refresh outcome from historical data.

The model would therefore provide **decision support** by producing a ranked opportunity list. Human review would still determine whether a page should actually be refreshed, expanded, protected, pruned, or monitored.

The purpose of ML is not to automatically make the content decision, but to prioritize which pages deserve attention first.

In [36]:
# Show the main signals available for the scoring problem

signal_columns = [
    "search_volume",
    "competition",
    "word_count",
    "ctr",
    "avg_position",
    "engagement_rate",
    "scroll_rate",
    "ai_traffic_pct",
    "days_since_last_update",
    "trend_pct"
]

print("Available signals for future scoring:")
display(df[signal_columns].head())

print("\nNumber of signals shown:", len(signal_columns))

Available signals for future scoring:

,search_volume,competition,word_count,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,days_since_last_update,trend_pct
0,10.0,0.67,3221.0,0.76,10.6,5.88,4.55,0.0,20,-41.4
1,90.0,0.01,2481.0,0.05,20.3,0.00,10.00,0.0,25,-57.7
2,0.0,0.00,3515.0,0.09,36.5,0.00,28.57,0.0,20,-60.9
3,10.0,0.00,NaN,0.49,6.2,1.28,3.45,0.0,22,-13.8
4,0.0,0.00,2803.0,0.13,44.0,0.00,24.29,0.0,14,-34.7

Number of signals shown: 10

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.